'use strict';
const historySeries=new Map(),highlightTargets=new Map(),projectionInputs=new Map(),projectionCache=new Map();
function toleranceForPrice(price){for(const [limit,diff] of [[5,.1],[10,.15],[15,.2],[20,.25],[30,.3],[40,.4],[50,.5],[60,.62],[70,.75],[80,.87],[90,.95],[100,1.1],[125,1.5],[150,2.5],[250,3],[300,4],[400,5],[500,6],[600,7],[700,7.5],[800,8],[1000,8.5],[1500,10]])if(price<limit)return diff;return price*.01;}
function classifyHistory(values,target){if(target===null||String(target).trim()===''||!Number.isFinite(Number(target)))throw Error('Enter a numeric comparison price.');target=Number(target);const tolerance=toleranceForPrice(target),counts={near:0,up:0,down:0};const classes=values.map(raw=>{if(raw===null||String(raw).trim()==='')return '';const value=Number(raw);if(!Number.isFinite(value))throw Error('The history contains an invalid price. Correct it before highlighting.');const kind=Math.abs(value-target)<=tolerance?'near':value<target?'down':'up';counts[kind]++;return kind;});const total=counts.near+counts.up+counts.down,pct={};for(const k of Object.keys(counts))pct[k]=total?counts[k]/total*100:0;return{classes,counts,pct,total,tolerance,score:Math.round((pct.up-.5*pct.down)*100)/100};}
function applyHistoryHighlight(){const input=$('#historyTarget'),cells=[...document.querySelectorAll('.reference-history td')];if(!input||!cells.length)return;try{const result=classifyHistory(cells.map(c=>c.textContent==='N/A'?null:c.textContent),input.value);highlightTargets.set(currentStock.ticker,input.value);cells.forEach((c,i)=>{c.classList.remove('price-highlight','history-near','history-up','history-down');if(result.classes[i])c.classList.add('history-'+result.classes[i]);});for(const [selector,key,label] of [['.flat-stat','near','Near'],['.up-stat','up','UP'],['.down-stat','down','Down']]){const el=document.querySelector(selector);el.innerHTML='<span class=stat-label>'+label+'</span><strong class=stat-count>'+result.counts[key]+'</strong><span class=stat-percent>'+Math.round(result.pct[key])+'%</span>';el.title=result.counts[key]+' times ('+result.pct[key].toFixed(2)+'%)';}$('#highlightScore').innerHTML='<span class=stat-label>Score</span><strong class=stat-count>'+result.score.toFixed(2)+'</strong>';$('#highlightScore').title='UP % − 0.5 × Down %; tolerance ±'+result.tolerance;$('#highlightStatus').textContent=result.total<60?'Compared '+result.total+' available prices; '+(60-result.total)+' missing.':'';}catch(e){$('#highlightStatus').textContent=e.message;}}
function simulateProjection(newestFirst,{runs=5000,random=Math.random,date=new Date()}={}){if(newestFirst.length!==60||newestFirst.some(v=>!Number.isFinite(v)||v<=0))throw Error('Enter exactly 60 positive closing prices, newest first. The current history includes a zero, missing, or invalid value.');const prices=[...newestFirst].reverse(),last=prices[59],returns=prices.slice(1).map((p,i)=>Math.log(p/prices[i])),mean=returns.reduce((a,b)=>a+b,0)/59,variance=returns.reduce((a,b)=>a+(b-mean)**2,0)/58,sigma=Math.sqrt(variance)*.8,sma5=prices.slice(-5).reduce((a,b)=>a+b)/5,sma20=prices.slice(-20).reduce((a,b)=>a+b)/20,momentum=(sma5-sma20)/sma20/5,blend=.5*mean+.5*momentum;
 const sums=new Float64Array(60),paths=new Float64Array(runs*60),pureDay=[],momDay=[],ends=[];
 for(let run=0;run<runs;run++){let pure=last,mom=last;for(let day=0;day<60;day++){const draw=random(),u1=draw===0?.000001:draw,u2=random(),z=Math.sqrt(-2*Math.log(u1))*Math.cos(2*Math.PI*u2);pure*=Math.exp(mean-.5*sigma*sigma+sigma*z);mom*=Math.exp(blend-.5*sigma*sigma+sigma*z);if(!Number.isFinite(pure)||!Number.isFinite(mom)||pure<=0||mom<=0)throw Error('These prices produce an unstable simulation. Check the history values.');if(day===0){pureDay.push(pure);momDay.push(mom);}paths[run*60+day]=mom;sums[day]+=mom;}ends.push({value:mom,index:run});}
 pureDay.sort((a,b)=>a-b);momDay.sort((a,b)=>a-b);ends.sort((a,b)=>a.value-b.value);const quantiles=a=>[.25,.5,.75].map(q=>a[Math.ceil(runs*q)-1]);const pure=quantiles(pureDay),momentumTargets=quantiles(momDay),low=Math.max(pure[0],momentumTargets[0]),high=Math.min(pure[2],momentumTargets[2]),medianIndex=ends[Math.ceil(runs*.5)-1].index,meanPath=Array.from(sums,v=>v/runs),samplePath=Array.from(paths.slice(medianIndex*60,(medianIndex+1)*60)),dates=[];const d=new Date(date);d.setHours(12,0,0,0);for(let i=0;i<60;i++){do{d.setDate(d.getDate()+1);}while(d.getDay()===0||d.getDay()===6);dates.push(new Date(d));}const stats=a=>({low:Math.min(...a),high:Math.max(...a),average:a.reduce((x,y)=>x+y,0)/a.length});return{runs,last,mean,momentum,sigma,pure,momentumTargets,low,high,overlap:low<=high,dates,meanPath,samplePath,meanStats:stats(meanPath),sampleStats:stats(samplePath)};
}
function renderProjection(stock){const host=$('#projectionContent');if(!host||priceTab!=='projection')return;const input=projectionInputs.get(stock.ticker)||historySeries.get(stock.ticker)||[];host.innerHTML='<div class="projection-toolbar"><strong>Dual Model · 5,000 simulations</strong><button id="rerunProjection">Run again</button></div><details class="projection-input"><summary>View / edit 60 closing prices</summary><label for="projectionPrices">Newest first; separate with spaces, commas, or new lines. Do not use thousands separators.</label><textarea id="projectionPrices"></textarea><button id="applyProjection">Apply prices & run 5,000 simulations</button></details><p class="projection-disclaimer">Simulation using uploaded Excel prices; not a guaranteed forecast. Weekends skipped; exchange holidays not excluded.</p><div id="projectionReport" role="status"></div>';
 $('#projectionPrices').value=input.join(', ');$('#rerunProjection').onclick=()=>{projectionCache.delete(stock.ticker);run();};$('#applyProjection').onclick=()=>{const values=$('#projectionPrices').value.trim().split(/[\s,;]+/).map(Number);projectionInputs.set(stock.ticker,values);projectionCache.delete(stock.ticker);run();};
 function run(){const report=$('#projectionReport');if(projectionCache.has(stock.ticker)){report.innerHTML=projectionReport(projectionCache.get(stock.ticker));return;}report.textContent='Running 5,000 simulations…';setTimeout(()=>{if(currentStock.ticker!==stock.ticker||priceTab!=='projection'||$('#projectionReport')!==report)return;try{const result=simulateProjection(projectionInputs.get(stock.ticker)||input);projectionCache.set(stock.ticker,result);report.innerHTML=projectionReport(result);}catch(e){report.textContent=e.message;}},0);}run();
}
function projectionReport(r){const money=n=>'₹'+n.toFixed(2),pct=n=>((n/r.last-1)*100).toFixed(2)+'%',date=d=>d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'});const range=r.overlap?`${money(r.low)} (${pct(r.low)}) – ${money(r.high)} (${pct(r.high)}) · Spread ${money(r.high-r.low)} (${((r.high-r.low)/r.last*100).toFixed(2)}%)`:'No overlapping 25th–75th percentile range between the two models.';const path=(title,values,stats)=>`<h3>${title}</h3><p>Low ${money(stats.low)} · High ${money(stats.high)} · Average ${money(stats.average)}</p><table class="projection-path"><thead><tr>${Array(4).fill('<th>Date</th><th>Price</th>').join('')}</tr></thead><tbody>${Array.from({length:15},(_,i)=>'<tr>'+[i,i+15,i+30,i+45].map(j=>`<td>${date(r.dates[j])}</td><td>${money(values[j])} ${values[j]>=(j?values[j-1]:r.last)?'↑':'↓'}</td>`).join('')+'</tr>').join('')}</tbody></table>`;return `<h3>Conservative range · ${date(r.dates[0])} · ${r.momentum>0?'Bullish':r.momentum<0?'Bearish':'Neutral'}</h3><p>${range}</p><table class="projection-targets"><thead><tr><th>Next session</th><th>Pure model</th><th>Momentum model</th></tr></thead><tbody>${['Low (25th percentile)','Base (50th percentile)','High (75th percentile)'].map((label,i)=>`<tr><td>${label}</td><td>${money(r.pure[i])}</td><td>${money(r.momentumTargets[i])}</td></tr>`).join('')}</tbody></table>${path('Smoothed expected path · mean of 5,000 runs',r.meanPath,r.meanStats)}${path('Representative path · median final price',r.samplePath,r.sampleStats)}`;}
// VBA Round uses round-to-even for halfway values.
function vbaRound(value,digits=0){const factor=10**digits,scaled=value*factor,lower=Math.floor(scaled),fraction=scaled-lower;return (fraction===.5?(lower%2===0?lower:lower+1):Math.round(scaled))/factor;}
function stockSupportLevels(values){const prices=[];for(const raw of values){if(raw===null||typeof raw==='boolean'||String(raw).trim()===''||!Number.isFinite(Number(raw))||Number(raw)<=0)break;prices.push(Number(raw));}if(prices.length<2)return{levels:[],text:'ERROR: Less than 2 valid numeric prices found (found '+prices.length+')',validCount:prices.length};
 const clusters=[];for(const price of prices){const existing=clusters.find(c=>Math.abs(price-c.rep)<=toleranceForPrice(price));if(existing){existing.count++;existing.sum+=price;existing.rep=existing.sum/existing.count;}else clusters.push({rep:price,count:1,sum:price});}
 const filtered=clusters.filter(c=>c.count>=2).sort((a,b)=>a.rep-b.rep),merged=[];for(const cluster of filtered){const previous=merged.at(-1);if(previous&&Math.abs(cluster.rep-previous.rep)<=toleranceForPrice(previous.rep)){previous.count+=cluster.count;previous.sum+=cluster.sum;previous.rep=previous.sum/previous.count;}else merged.push({...cluster});}
 const all=merged.sort((a,b)=>b.rep-a.rep).map(c=>({...c,price:vbaRound(c.rep,c.rep<10?2:c.rep<100?1:0)})),current=prices[0],above=all.filter(c=>c.price>current).sort((a,b)=>a.price-b.price),below=all.filter(c=>c.price>0&&c.price<current).sort((a,b)=>b.price-a.price);const selected=[...above.slice(0,2),...below.slice(0,3)];for(const extra of [...above.slice(2),...below.slice(3)])if(selected.length<5)selected.push(extra);selected.sort((a,b)=>b.price-a.price);
 let closest=-1,distance=999999999;selected.forEach((c,i)=>{const d=Math.abs(current-c.price);if(d<distance){distance=d;closest=i;}});const levels=selected.map((c,i)=>({...c,closest:i===closest,label:c.price.toFixed(c.price<10?2:c.price<100?1:0),kind:Math.abs(c.price-current)<=toleranceForPrice(current)?'near':c.price>current?'up':'down'}));const raw=levels.map(c=>c.closest?'**'+c.label+'/'+c.count+'***':c.label+' ('+c.count+')').join(', ');return{levels,current,validCount:prices.length,raw,text:raw?raw.replaceAll('***','〕').replaceAll('**','▶︎•〔'):'No support levels found'};
}
function renderSupportLevels(stock){const host=$('#supportLevels');if(!host)return;const source=stock.sourceSupport||'',valid=source&&!source.startsWith('#')&&!source.startsWith('ERROR'),current=stock.history[0];host.title='Support levels supplied by the Excel workbook.';host.innerHTML='<b class=levels-heading>Support levels</b><span class=levels-chips>'+(valid?source.split(',').map(part=>{const price=Number(part.match(/[0-9]+(?:\.[0-9]+)?/)?.[0]),kind=Number.isFinite(current)&&Math.abs(price-current)<=toleranceForPrice(current)?'near':price<current?'down':'up';return '<span class="support-level support-'+kind+'">'+esc(part.trim())+'</span>';}).join(''):'Not Available')+'</span>';}
// Read each table column top-to-bottom, left-to-right: newest first.
// Reversing yields rightmost bottom-to-top, then the next column leftward.
function historyFromTableRows(rows){if(!rows.length)return[];return Array.from({length:rows[0].length},(_,column)=>rows.map(row=>row[column])).flat();}
function historySparkline(newestFirst){
 const chronological=[...newestFirst].reverse(),valid=chronological.filter(v=>Number.isFinite(v)&&v>=0);
 if(!valid.length)return '<span class="history-chart-empty">History unavailable</span>';
 const min=Math.min(...valid),max=Math.max(...valid),span=max-min,segments=[],dots=[];let segment=[];
 chronological.forEach((price,i)=>{if(!Number.isFinite(price)||price<0){if(segment.length)segments.push(segment);segment=[];return;}const x=6+i*288/Math.max(1,chronological.length-1),y=span?65-(price-min)/span*55:37;segment.push({x,y});dots.push(`<circle class="chart-hover-point" cx="${x.toFixed(2)}" cy="${y.toFixed(2)}" r="5"><title>${i===chronological.length-1?'Latest':(chronological.length-i)+' days ago'}: ₹${price.toFixed(2)}</title></circle>`);});
 if(segment.length)segments.push(segment);
 const coordinates=points=>points.map((p,i)=>(i?'L':'M')+p.x.toFixed(2)+','+p.y.toFixed(2)).join(' '),line=segments.map(coordinates).join(' '),area=segments.map(points=>coordinates(points)+` L${points.at(-1).x.toFixed(2)},70 L${points[0].x.toFixed(2)},70 Z`).join(' '),latest=newestFirst[0],previous=newestFirst[1],hasLatest=Number.isFinite(latest)&&latest>=0,hasChange=hasLatest&&Number.isFinite(previous)&&previous>0,change=latest-previous,last=hasLatest?segments.at(-1)?.at(-1):null;
 return `<div class="price-card-summary"><span class="price-card-label">Latest price</span><strong>${hasLatest?'₹'+latest.toFixed(2):'N/A'}</strong><span class="price-card-change ${hasChange?(change<0?'negative':'positive'):''}" title="Change from the previous closing price">${hasChange?(change>0?'+':'')+change.toFixed(2)+' ('+(change>0?'+':'')+(change/previous*100).toFixed(2)+'%)':'Change unavailable'}</span><span class="price-card-caption">Previous close</span></div><div class="price-card-plot"><span class="price-card-period">60D VIEW</span><svg class="history-sparkline modern-history-chart" viewBox="0 0 300 76" preserveAspectRatio="none" role="img" aria-label="60-day price history, oldest on the left and latest on the right"><title>60-day closing prices in table order, oldest to newest. Uploaded Excel snapshot; unavailable prices are shown as gaps.</title><defs><linearGradient id="history-area-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#647a96" stop-opacity=".38"/><stop offset="100%" stop-color="#c8d3df" stop-opacity=".03"/></linearGradient></defs><path d="M6 70 H294" stroke="#e7edf4" fill="none"/><path d="${area}" fill="url(#history-area-fill)"/><path d="${line}" fill="none" stroke="#172c49" stroke-width="1.8" stroke-linejoin="round" stroke-linecap="round" vector-effect="non-scaling-stroke"/>${last?`<circle cx="${last.x}" cy="${last.y}" r="6" fill="#216fb5" opacity=".12"/><circle cx="${last.x}" cy="${last.y}" r="2.6" fill="#173d67"/>`:''}<g>${dots.join('')}</g></svg><div class="price-card-axis"><span>60 days ago</span><span>Latest</span></div></div>`;
}

function bindHistoryChart(newestFirst){
 const svg=document.querySelector('.modern-history-chart'),card=document.querySelector('.history-chart-row');if(!svg||!card||!svg.querySelector)return;
 const summary=card.querySelector('.price-card-summary'),label=summary.querySelector('.price-card-label'),priceEl=summary.querySelector('strong'),changeEl=summary.querySelector('.price-card-change'),caption=summary.querySelector('.price-card-caption');
 const original=summary.innerHTML,values=[...newestFirst].reverse(),valid=values.filter(v=>Number.isFinite(v)&&v>=0),min=Math.min(...valid),span=Math.max(...valid)-min;
 const ns='http://www.w3.org/2000/svg',marker=document.createElementNS(ns,'g');marker.setAttribute('class','chart-cursor');marker.setAttribute('pointer-events','none');marker.innerHTML='<line y1="0" y2="70" stroke="#3c7ca7" stroke-dasharray="3 3"/><circle r="3.5" fill="#fff" stroke="#173d67" stroke-width="1.8"/>';svg.appendChild(marker);marker.style.display='none';
 let index=values.length-1;
 function show(i){index=Math.max(0,Math.min(values.length-1,i));const price=values[index],previous=values[index-1];if(!Number.isFinite(price)||price<0)return;const x=6+index*288/Math.max(1,values.length-1),y=span?65-(price-min)/span*55:37;marker.style.display='';const line=marker.querySelector('line'),dot=marker.querySelector('circle');line.setAttribute('x1',x);line.setAttribute('x2',x);dot.setAttribute('cx',x);dot.setAttribute('cy',y);label.textContent=index===values.length-1?'Latest price':(values.length-index)+' days ago';priceEl.textContent='₹'+price.toFixed(2);const ok=Number.isFinite(previous)&&previous>0,delta=price-previous;changeEl.textContent=ok?(delta>0?'+':'')+delta.toFixed(2)+' ('+(delta>0?'+':'')+(delta/previous*100).toFixed(2)+'%)':'Change unavailable';changeEl.className='price-card-change '+(ok?(delta<0?'negative':'positive'):'');caption.textContent='Previous close';svg.setAttribute('aria-label',label.textContent+': '+priceEl.textContent);}
 function move(e){const box=svg.getBoundingClientRect();show(Math.round(((e.clientX-box.left)/box.width*300-6)/288*(values.length-1)));}
 function reset(){marker.style.display='none';const fresh=document.createElement('div');fresh.innerHTML=original;label.textContent=fresh.querySelector('.price-card-label').textContent;priceEl.textContent=fresh.querySelector('strong').textContent;changeEl.textContent=fresh.querySelector('.price-card-change').textContent;changeEl.className=fresh.querySelector('.price-card-change').className;caption.textContent=fresh.querySelector('.price-card-caption').textContent;svg.setAttribute('aria-label','60-day price history, oldest on the left and latest on the right');}
 svg.setAttribute('tabindex','0');svg.setAttribute('role','group');svg.setAttribute('aria-description','Move across the chart or use left and right arrow keys to inspect daily prices.');svg.addEventListener('pointermove',move);svg.addEventListener('pointerdown',e=>{svg.setPointerCapture(e.pointerId);move(e);});svg.addEventListener('pointerleave',reset);svg.addEventListener('pointercancel',reset);svg.addEventListener('blur',reset);svg.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();show(e.key==='Home'?0:e.key==='End'?values.length-1:index+(e.key==='ArrowRight'?1:-1));}});
}

const sentimentAdjustments={'Bubble':20,'Extremely Bullish':10,'Bullish':5,'Neutral/SideWay':0,'Bearish':-5,'Severely Bearish':-10,'Panic/Market crash':-25};
function tradingRanges(low,high,sentiment,expected,low52=null,high52=null){if(!Number.isFinite(low)||!Number.isFinite(high)||low<=0||high<low)return{unavailable:true,expected,entry:[],exit:[],capped:false};const adjustment=sentimentAdjustments[sentiment]??0,entry=[low,high].map(v=>v*(1+adjustment/100)),exit=[low,high].map(v=>v*(1+(adjustment+expected)/100));const bounded=Number.isFinite(low52)&&Number.isFinite(high52)&&low52>0&&high52>=low52,rawExit=[...exit];if(bounded){exit[0]=Math.max(low52,Math.min(high52,exit[0]));exit[1]=Math.max(low52,Math.min(high52,exit[1]));}const capped=exit.some((v,i)=>v!==rawExit[i]);const cents=v=>Math.round((v+Number.EPSILON*Math.abs(v))*100)/100;return{adjustment,expected,capped,bounded,rawExit,entry:entry.map(cents),exit:exit.map(cents),entryAverage:cents((entry[0]+entry[1])/2),exitAverage:cents((exit[0]+exit[1])/2)};}
function selectedTradingRanges(s){return tradingRanges(s.intrinsicMin,s.intrinsicMax,$('#overviewSentiment').value||'Neutral/SideWay',Number($('#overviewReturn').value||12),s.low52,s.high52);}
function renderValuation(s){const r=selectedTradingRanges(s);if(r.unavailable){$('#valuationEstimate').innerHTML='<div class=valuation-unavailable>Valuation unavailable</div><p class=valuation-note>The workbook has no valid intrinsic value range for this ticker.</p>';return;}const money=v=>'₹'+v.toFixed(2),min=Math.min(...r.entry,...r.exit),max=Math.max(...r.entry,...r.exit),position=v=>max===min?50:Math.max(0,Math.min(100,(v-min)/(max-min)*100));$('#valuationEstimate').innerHTML=`<span class="valuation-eyebrow">Estimated fair value</span><div class="valuation-range">${money(s.intrinsicMin)} – ${money(s.intrinsicMax)}</div><p class="valuation-note">Valuation base · ${esc($('#overviewSentiment').value||'Neutral/SideWay')} (${r.adjustment>0?'+':''}${r.adjustment}%)</p><div class="valuation-zones"><div class="value-zone entry-zone"><span>Entry zone</span><strong>${r.entry.map(money).join(' – ')}</strong><small>Average <b>${money(r.entryAverage)}</b></small></div><div class="value-zone exit-zone"><span>Exit zone</span><strong>${r.exit.map(money).join(' – ')}</strong><small>Average <b>${money(r.exitAverage)}</b></small></div></div><div id="priceExplorer" class="valuation-comparison"></div><p class="range-formula" title="Entry = valuation × (1 + sentiment adjustment). Exit = valuation × (1 + sentiment adjustment + expected return), limited to the 52-week low–high range. The limit may reduce the target return.">Target return ${r.expected}% · ${r.capped?'exit adjusted to 52W bounds':r.bounded?'exit within 52W bounds':'52W bounds unavailable'}</p>`;renderPriceExplorer(s,r);}

function priceScenario(price,current,r){
  return {difference:current>0?price-current:null,change:current>0?(price/current-1)*100:null,returnPct:(r.exitAverage/price-1)*100,
    zone:price<r.entry[0]?'Below entry range':price<=r.entry[1]?'Within entry range':price<r.exit[0]?'Between entry and exit':price<=r.exit[1]?'Within exit range':'Above exit range'};
}
function renderPriceExplorer(s,r){
  const root=$('#priceExplorer'),current=Number.isFinite(s.price)&&s.price>0?s.price:null;
  if(!current){root.innerHTML='<span class="comparison-heading">Price comparison unavailable</span><p class="valuation-note">Current price is unavailable for this stock.</p>';return;}
  const values=[...r.entry,...r.exit,current],lo=Math.min(...values),hi=Math.max(...values),pad=Math.max((hi-lo)*.15,hi*.05),min=Math.max(.01,Math.floor((lo-pad)*100)/100),max=Math.ceil((hi+pad)*100)/100;
  const money=v=>'₹'+v.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}),pos=v=>(v-min)/(max-min)*100;
  root.innerHTML=`<div class="explorer-heading"><span class="comparison-heading">What if I buy at…</span><button type="button" class="explorer-reset">Reset</button></div><label class="explorer-price">Your buying price <span>₹ <input class="explorer-number" type="number" min="${min}" max="${max}" step="0.01" value="${current.toFixed(2)}" aria-label="Your buying price"></span></label><div class="explorer-slider"><div class="explorer-reference entry" style="left:${pos(r.entryAverage)}%" title="Entry average ${money(r.entryAverage)}"></div><div class="explorer-reference exit" style="left:${pos(r.exitAverage)}%" title="Exit average ${money(r.exitAverage)}"></div><div class="explorer-reference current" style="left:${pos(current)}%" title="Current price ${money(current)}"></div><input type="range" min="${min}" max="${max}" step="0.01" value="${current}" aria-label="Explore buying price"></div><div class="explorer-legend"><span class="entry">Entry avg <b>${money(r.entryAverage)}</b></span><span class="current">Current price <b>${money(current)}</b></span><span class="exit">Exit avg <b>${money(r.exitAverage)}</b></span></div><div class="explorer-results" aria-live="polite" aria-atomic="true"></div><p class="explorer-hint">Drag the blue point to compare. Scenario return, not a forecast.</p>`;
  const slider=root.querySelector('input[type=range]'),number=root.querySelector('input[type=number]'),results=root.querySelector('.explorer-results');
  function update(value,writeNumber=true){
    const price=Math.max(min,Math.min(max,Math.round(value*100)/100)),x=priceScenario(price,current,r),signed=v=>(v>0?'+':'')+v.toFixed(2)+'%';
    slider.value=price;if(writeNumber)number.value=price.toFixed(2);
    slider.setAttribute('aria-valuetext',money(price)+', '+x.zone+', return to exit average '+signed(x.returnPct));
    results.innerHTML=`<div><span>vs current price</span><strong>${x.difference===0?'Same price':money(Math.abs(x.difference))+(x.difference<0?' lower':' higher')}</strong><small>${signed(x.change)}</small></div><div><span>Return to exit avg</span><strong class="${x.returnPct>=0?'positive':'negative'}">${signed(x.returnPct)}</strong><small>${x.zone}</small></div>`;
  }
  slider.addEventListener('input',()=>update(Number(slider.value)));
  number.addEventListener('input',()=>{const n=number.valueAsNumber;if(Number.isFinite(n)&&n>=min&&n<=max)update(n,false);});
  number.addEventListener('change',()=>update(Number.isFinite(number.valueAsNumber)?number.valueAsNumber:current));
  root.querySelector('.explorer-reset').addEventListener('click',()=>update(current));update(current);
}
