function ensureXLSX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='js/xlsx.full.min.js';s.onload=()=>resolve(window.XLSX);s.onerror=()=>reject(new Error('Failed to load Excel export library'));document.head.appendChild(s);});}
'use strict';
const columns=[
 ['name','Company','text','Identity'],['ticker','Ticker','text','Identity'],['sector','Sector','select','Identity'],
 ['price','LTP','money','Price & trend'],['marketCap','Market cap','cr','Fundamentals'],['pe','P/E ratio','ratio','Fundamentals'],['roe','ROE','pct','Fundamentals'],['de','Debt / Equity','ratio','Fundamentals'],['profitGrowth','Profit growth YoY','pct','Fundamentals'],['revenueGrowth','Revenue growth YoY','pct','Fundamentals'],['dividend','Dividend yield','pct','Fundamentals'],['fcf','FCF yield','pct','Fundamentals'],['holding','Promoter holding','pct','Fundamentals'],['book','Book value','money','Fundamentals'],['peg','PEG ratio','ratio','Fundamentals'],['ev','EV / EBITDA','ratio','Fundamentals'],['eps','EPS','money','Fundamentals'],['current','Current ratio','ratio','Fundamentals'],['quick','Quick ratio','ratio','Fundamentals'],['beta','Beta','ratio','Price & trend'],['intrinsicMin','Intrinsic value: low','money','Fundamentals'],['intrinsicMax','Intrinsic value: high','money','Fundamentals'],['score','Fundamental score','score','Fundamentals'],['volume','Volume','int','Price & trend'],['volumeAvg','Average volume','int','Price & trend'],['low52','52-week low','money','Price & trend'],['high52','52-week high','money','Price & trend'],['low3','2.5-month low','money','Price & trend'],['high3','2.5-month high','money','Price & trend'],['dma200','200 DMA','money','Price & trend'],['dma90','90 DMA','money','Price & trend'],['ratio52','52W vs current price','pct','Price & trend'],['ratio15','15W vs current price','pct','Price & trend'],['up','Up days','pct','Price & trend'],['growth3','3M net growth','pct','Price & trend'],['averageMove','Average move','pct','Price & trend'],['type','Ticker type','select','Identity'],['sentiment','Market sentiment','select','Price & trend'],['expectedReturn','Expected return','pct','Fundamentals']
,['oldScore','Fundamental score (old)','score','Fundamentals'],['valueRank','Value rank','ratio','Fundamentals'],['intrinsicPercent','Intrinsic value difference','pct','Fundamentals'],['paidUp','Paid up','money','Fundamentals'],['effort','Effort','pct','Price & trend'],['efficiency','Efficiency','pct','Price & trend'],['alternatePe','PE (alternate source column)','ratio','Fundamentals']
].map(([key,label,type,group])=>({key,label,type,group}));
const stocks=STOCK_DATABASE.stocks;
const round=x=>Math.round(x*100)/100;
const defaults=['name','sector','price','marketCap','pe','roe','de','profitGrowth','revenueGrowth','score'];
let visible=new Set(defaults),filters={},query='',sortKey='name',sortDirection=1,page=1,group='all',filterQuery='';const pageSize=stocks.length;
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const units={pct:'%',money:'₹',cr:'₹ Cr',ratio:'×',int:'',score:'/100'};
function display(v,c){if(v===null||v===undefined||(['text','select'].includes(c.type)?false:!Number.isFinite(v)))return 'N/A';if(c.type==='text'||c.type==='select')return String(v);const fmt=new Intl.NumberFormat('en-IN',{maximumFractionDigits:c.type==='int'?0:2,minimumFractionDigits:c.type==='int'?0:2});return(c.type==='money'?'₹':'')+fmt.format(v)+(c.type==='pct'?'%':c.type==='cr'?' Cr':'');}
const multiFields=new Set(['ticker','name','sector']);
function matchText(value,filter,key){
 const terms=(multiFields.has(key)?filter.split(','):[filter]).map(t=>t.trim().toLowerCase()).filter(Boolean);
 if(!terms.length)return true;
 const text=String(value).toLowerCase();
 return terms.some(term=>key==='ticker'?text===term.replace(/^nse:/,'').replace(/\.ns$/,''):text.includes(term));
}
function matches(stock){if(query&&!columns.some(c=>[String(stock[c.key]??''),display(stock[c.key],c)].some(v=>v.toLowerCase().includes(query.toLowerCase()))))return false;return Object.entries(filters).every(([key,f])=>{let v=stock[key];if(v===null||v===undefined)return false;if(typeof f==='string')return matchText(v,f,key);return(f.min===''||v>=Number(f.min))&&(f.max===''||v<=Number(f.max));});}
function results(){return stocks.filter(matches).sort((a,b)=>{let x=a[sortKey],y=b[sortKey];if(x==null)return y==null?0:1;if(y==null)return -1;return(typeof x==='number'?x-y:String(x).localeCompare(String(y)))*sortDirection;});}
function renderFilters(){let html='';let lastGroup='';for(const c of columns){if(group!=='all'&&!(group==='Fundamentals'?c.group==='Fundamentals':c.group==='Price & trend'))continue;if(filterQuery&&!c.label.toLowerCase().includes(filterQuery))continue;if(c.group!==lastGroup){html+=`<div class="filter-group-label">${esc(c.group.toUpperCase())}</div>`;lastGroup=c.group;}const f=filters[c.key];html+=`<div class="filter-item"><label for="f-${c.key}">${esc(c.label)}${units[c.type]?`<small>${units[c.type]}</small>`:''}</label>`;if(c.type==='select'&&c.key!=='sector'){const opts=[...new Set(stocks.map(s=>s[c.key]).filter(v=>v!=null))].sort();html+=`<select id="f-${c.key}" data-filter="${c.key}"><option value="">All ${c.key==='sector'?'sectors':c.key==='type'?'types':'sentiments'}</option>${opts.map(v=>`<option${f===v?' selected':''}>${esc(v)}</option>`).join('')}</select>`;}else if(c.type==='text'||c.key==='sector'){html+=`<input class="text-filter" id="f-${c.key}" data-filter="${c.key}" value="${esc(f||'')}" placeholder="${c.key==='ticker'?'LUPIN, NSE:ITC':c.key==='name'?'Lupin, Tata':'Healthcare, Technology'}"${c.key==='sector'?' list="sectorOptions"':''}><small class="multi-help">Separate values with commas. Matches any value.</small>${c.key==='sector'?`<datalist id="sectorOptions">${[...new Set(stocks.map(s=>s.sector))].sort().map(v=>`<option value="${esc(v)}"></option>`).join('')}</datalist>`:''}`;}else{html+=`<div class="range-inputs"><input id="f-${c.key}" data-filter="${c.key}" data-bound="min" type="number" step="any" placeholder="Min" aria-label="${esc(c.label)} minimum" value="${esc(f?.min??'')}"><span>to</span><input data-filter="${c.key}" data-bound="max" type="number" step="any" placeholder="Max" aria-label="${esc(c.label)} maximum" value="${esc(f?.max??'')}"></div>`;}html+='</div>';}
 $('#filterList').innerHTML=html||'<p class="field-label">No matching filters.</p>';}
function renderColumns(){ $('#colCount').textContent=visible.size;$('#columnChoices').innerHTML=columns.map(c=>`<label><input type="checkbox" data-column="${c.key}"${visible.has(c.key)?' checked':''}${c.key==='name'?' disabled':''}>${esc(c.label)}</label>`).join('');}
function render(){const found=results(),pages=Math.max(1,Math.ceil(found.length/pageSize));page=Math.min(page,pages);const cols=columns.filter(c=>visible.has(c.key));$('#downloadBtn').disabled=found.length===0;$('#resultCount').innerHTML=`<strong>${found.length}</strong> of ${stocks.length} stocks`;$('#thead').innerHTML='<tr>'+cols.map(c=>`<th scope="col"${sortKey===c.key?` aria-sort="${sortDirection===1?'ascending':'descending'}"`:''}><button data-sort="${c.key}" aria-label="Sort by ${esc(c.label)}">${esc(c.label)}<small>${sortKey===c.key?(sortDirection===1?'↑':'↓'):'↕'}</small></button></th>`).join('')+'</tr>';
 const chunk=found.slice((page-1)*pageSize,page*pageSize);$('#tbody').innerHTML=chunk.map(s=>'<tr>'+cols.map(c=>{let v=s[c.key],text=esc(display(v,c)),cl='';if(v==null)cl='missing';else if(['profitGrowth','revenueGrowth','growth3','expectedReturn'].includes(c.key))cl=v>=0?'positive':'negative';if(c.key==='name')text=`<button class="company-name company-link" data-open-stock="${esc(s.ticker)}">${esc(s.name)}</button><span class="ticker">NSE:${esc(s.ticker)}</span><button class="watch-star" data-watch-stock="${esc(s.ticker)}" aria-label="Add ${esc(s.name)} to watchlist" aria-pressed="false">☆</button>`;if(c.key==='sector')text=`<span class="sector-tag">${text}</span>`;if(c.key==='score')text=`<span class="score">${text}</span>`;return`<td class="${cl}">${text}</td>`;}).join('')+'</tr>').join('');$('#empty').hidden=found.length!==0;$('#rangeCount').textContent=found.length?`${(page-1)*pageSize+1}–${Math.min(page*pageSize,found.length)} of ${found.length} results`:'0 results';$('#pageLabel').textContent=`${page} / ${pages}`;$('#prev').disabled=page===1;$('#next').disabled=page>=pages;
 const active=Object.entries(filters);$('#appliedRow').hidden=!active.length;$('#chips').innerHTML=active.map(([k,f])=>{const c=columns.find(c=>c.key===k);let val=typeof f==='string'?f:`${f.min!==''?`≥ ${f.min}`:''}${f.min!==''&&f.max!==''?' · ':''}${f.max!==''?`≤ ${f.max}`:''}`;return`<button class="chip" data-remove="${k}" aria-label="Remove ${esc(c.label)} filter">${esc(c.label)}: ${esc(val)} <span>×</span></button>`;}).join('');}
function reset(){filters={};query='';page=1;$('#search').value='';renderFilters();render();}
$('#search').addEventListener('input',e=>{query=e.target.value.trim();page=1;render();});$('#filterSearch').addEventListener('input',e=>{filterQuery=e.target.value.toLowerCase();renderFilters();});
$('#filterList').addEventListener('input',e=>{const el=e.target,k=el.dataset.filter;if(!k)return;if(el.dataset.bound){const f=filters[k]&&typeof filters[k]==='object'?filters[k]:{min:'',max:''};f[el.dataset.bound]=el.value;if(f.min===''&&f.max==='')delete filters[k];else filters[k]=f;}else{if(el.value)filters[k]=el.value;else delete filters[k];}page=1;render();});
$('.filter-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;document.querySelectorAll('[data-group]').forEach(x=>x.classList.toggle('active',x===b));renderFilters();});$('#reset').onclick=reset;$('#clearEmpty').onclick=reset;
$('#thead').addEventListener('click',e=>{const b=e.target.closest('[data-sort]');if(!b)return;const k=b.dataset.sort;sortDirection=k===sortKey?-sortDirection:1;sortKey=k;page=1;render();});$('#chips').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(!b)return;delete filters[b.dataset.remove];page=1;renderFilters();render();});$('#columnsBtn').onclick=()=>{const p=$('#columnsPanel');p.hidden=!p.hidden;$('#columnsBtn').setAttribute('aria-expanded',String(!p.hidden));};$('#columnChoices').addEventListener('change',e=>{const k=e.target.dataset.column;if(!k)return;if(e.target.checked)visible.add(k);else visible.delete(k);renderColumns();render();});$('#showAll').onclick=()=>{visible=new Set(columns.map(c=>c.key));renderColumns();render();};$('#restoreColumns').onclick=()=>{visible=new Set(defaults);renderColumns();render();};$('#prev').onclick=()=>{page--;render();};$('#next').onclick=()=>{page++;render();};
$('.quick-presets').addEventListener('click',e=>{const b=e.target.closest('[data-preset]');if(!b)return;const p=b.dataset.preset;const ranges={value:{pe:{min:'',max:'20'},de:{min:'',max:'1'}},quality:{roe:{min:'15',max:''},de:{min:'',max:'.5'}},income:{dividend:{min:'2',max:''}},growth:{profitGrowth:{min:'20',max:''},revenueGrowth:{min:'15',max:''}}};filters=ranges[p];query='';$('#search').value='';page=1;renderFilters();render();});
renderFilters();renderColumns();render();
// Optional browser-native agent access uses the same actions as the visible screen.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'filter_stocks',title:'Filter stocks',description:'Set the visible screener search and numeric or text filters. Data comes from the uploaded Excel snapshot.',inputSchema:{type:'object',properties:{search:{type:'string'},filters:{type:'object',additionalProperties:{oneOf:[{type:'string'},{type:'object',properties:{min:{type:'number'},max:{type:'number'}},additionalProperties:false}]}}},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Expected an object');if(input.search!==undefined&&typeof input.search!=='string')throw Error('Search must be text');let next={};for(const [k,v]of Object.entries(input.filters||{})){const c=columns.find(c=>c.key===k);if(!c)throw Error('Unknown column: '+k);if(['text','select'].includes(c.type)){if(typeof v!=='string')throw Error('Expected text for '+k);if(v)next[k]=v;}else{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Expected a numeric range');for(const b of ['min','max'])if(v[b]!==undefined&&(typeof v[b]!=='number'||!Number.isFinite(v[b])))throw Error('Range must contain finite numbers');if(v.min!==undefined&&v.max!==undefined&&v.min>v.max)throw Error('Minimum exceeds maximum');next[k]={min:v.min??'',max:v.max??''};}}filters=next;query=input.search||'';$('#search').value=query;page=1;renderFilters();render();return{count:results().length,tickers:results().map(s=>s.ticker),dataSource:STOCK_DATABASE.metadata.source};}})).catch(()=>{});}catch{}}

function createDownloadWorkbook(){
 const selected=results();
 const label=c=>c.label+(c.type==='pct'?' (%)':c.type==='money'?' (INR)':c.type==='cr'?' (INR Cr)':c.type==='score'?' (/100)':'');
 const data=[columns.map(label),...selected.map(stock=>columns.map(c=>stock[c.key]??'Not Available'))];
 const sheet=XLSX.utils.aoa_to_sheet(data);
 sheet['!cols']=columns.map(c=>({wch:c.key==='name'?30:c.key==='sector'?24:21}));
 const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Filtered stocks');
 const info=XLSX.utils.aoa_to_sheet([['RightTicker screener export'],['Data status',STOCK_DATABASE.metadata.note],['Source file',STOCK_DATABASE.metadata.source],['Imported at',STOCK_DATABASE.metadata.importedAt],['Market-data timestamp','Not supplied'],['Cap group method',STOCK_DATABASE.metadata.capClassification],['Sector average method',STOCK_DATABASE.metadata.sectorAverages],['Exported at',new Date().toISOString()],['Rows',selected.length],['Search',query],['Filters',JSON.stringify(filters)],['Sort',sortKey+' '+(sortDirection===1?'ascending':'descending')],['Coverage','All filtered rows and '+columns.length+' screener columns, plus original workbook values in Source data.']]);
 info['!cols']=[{wch:20},{wch:100}];XLSX.utils.book_append_sheet(book,info,'Export details');XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([STOCK_DATABASE.headers,...selected.map(s=>s.sourceValues)]),'Source data');return book;
}
$('#downloadBtn').onclick=()=>{
 try{const book=createDownloadWorkbook();XLSX.writeFile(book,'RightTicker-Filtered-Stocks.xls',{bookType:'biff8'});$('#downloadStatus').textContent='Downloaded '+results().length+' stocks.';}
 catch(error){$('#downloadStatus').textContent='Download could not be created. Please try again.';}
};

const tableViewport=$('.table-wrap');
function syncScrollControls(){
 const maxX=Math.max(0,tableViewport.scrollWidth-tableViewport.clientWidth),maxY=Math.max(0,tableViewport.scrollHeight-tableViewport.clientHeight);
 $('#horizontalScroll').max=String(maxX);$('#horizontalScroll').value=String(Math.max(0,tableViewport.scrollLeft));
 $('#horizontalScroll').disabled=maxX===0;$('#scrollLeft').disabled=tableViewport.scrollLeft<=1;$('#scrollRight').disabled=tableViewport.scrollLeft>=maxX-1;
 $('#scrollUp').disabled=tableViewport.scrollTop<=1;$('#scrollDown').disabled=tableViewport.scrollTop>=maxY-1;
}
function scrollTable(x,y){tableViewport.scrollBy({left:x,top:y,behavior:'auto'});syncScrollControls();}
$('#scrollLeft').onclick=()=>scrollTable(-Math.max(120,tableViewport.clientWidth*.65),0);
$('#scrollRight').onclick=()=>scrollTable(Math.max(120,tableViewport.clientWidth*.65),0);
$('#scrollUp').onclick=()=>scrollTable(0,-Math.max(60,tableViewport.clientHeight*.65));
$('#scrollDown').onclick=()=>scrollTable(0,Math.max(60,tableViewport.clientHeight*.65));
$('#horizontalScroll').addEventListener('input',e=>{tableViewport.scrollLeft=Number(e.target.value);syncScrollControls();});
function fitViewport(){const height=window.visualViewport?.height||window.innerHeight;document.documentElement.style.setProperty('--app-height',Math.floor(height)+'px');requestAnimationFrame(syncScrollControls);}
window.addEventListener('resize',fitViewport);window.addEventListener('orientationchange',fitViewport);window.visualViewport?.addEventListener('resize',fitViewport);
tableViewport.addEventListener('scroll',syncScrollControls,{passive:true});
if(typeof ResizeObserver!=='undefined')new ResizeObserver(syncScrollControls).observe(tableViewport);
if(typeof MutationObserver!=='undefined')new MutationObserver(()=>requestAnimationFrame(syncScrollControls)).observe($('#thead'),{childList:true});
fitViewport();
